### ISSUE TITLE
Avatar not displayed correctly

### ISSUE THREAD

**Issue by JohnnyKing94** [malko/rocketchat-gitlab-hook#13]
I found a bug related to the avatars: when gravatar is used, i can see correctly the image of the user, but if the guy who pushed the commits doesn't have a gravatar image (just a normal uploaded avatar), i get no images, just a not found link pointing to a nonexistent path

This is the result with gravatar
LINK: https://www.dropbox.com/s/zhhr2aybfcodgc6/Screenshot%202017-07-10%2018.32.12.jpg?dl=0

This is the result without gravatar (just normal avatar uploaded)
LINK: https://www.dropbox.com/s/gul0nc94i95m1sw/Screenshot%202017-07-10%2018.32.00.jpg?dl=0
This is the wrong path used: `/uploads/system/user/avatar/921231/avatar.png`

**Comment by malko** [comment]
This seems to be due to the gitlab hook reporting a wrong avatar url you should open a bug on gitlab for this to be solved. The only way i see to solve this our side is to rewrite url avatar but then when gitlab will correctly report avatars urls again we will have to fix it back. I'm not fond of that.

**Comment by JohnnyKing94** [comment]
Anyway i just found out i reported the wrong link for gravatar, this is how i see when gravatar is used: https://www.dropbox.com/s/zhhr2aybfcodgc6/Screenshot%202017-07-10%2018.32.12.jpg?dl=0

I'll try to report on gitlab then... thank you ;)

**Comment by malko** [comment]
there's already an open issues https://gitlab.com/gitlab-org/gitlab-ce/issues/34339

**Comment by JohnnyKing94** [comment]
Opened 2 weeks and still no user or tag assigned? LOL this breaks my heart 😄

**Comment by Bubu** [comment]
Yeah, I'm also looking forward to get this foxed by gitlab.

**Comment by JohnnyKing94** [comment]
We're having some develops on the issue: https://gitlab.com/gitlab-org/gitlab-ce/issues/34339

**Comment by malko** [comment]
Seems like solved in Gitlab 10.1. Anyone already tested it ?

**Comment by JohnnyKing94** [comment]
Yeah they fixed... forgot to close the issue... thank you anyway :P
