### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by anthonylavado** [malko/rocketchat-gitlab-hook#14]
Hi there!
Thank you for putting together this script and sharing it with both the Rocket.Chat and GitHub community.

To help assure the continued, safe use of this script, would you consider adding a license to the repository? It would be greatly appreciated if possible.

For some suggestions, I recommend checking the GitHub created [Choose A License](https://choosealicense.com).

**Comment by malko** [comment]
Ok you're right, it's now under MIT License
