### ISSUE TITLE
Unknown on Git commit messages

### ISSUE THREAD

**Issue by oximer** [malko/rocketchat-gitlab-hook#19]
I'm getting 

`Tue, 06 Feb 2018 17:11:30 GMT b04882ba by Unknown: Commit message`

on git commit messages.

**Comment by malko** [comment]
Hi,
What is your gitlab and rocketchat version please ?

**Comment by jrisch** [comment]
I'm experiencing the same problem. I'm using latest Gitlab version (10.7.3) and version 0.63.3 of Rocket.chat.

**Comment by malko** [comment]
close because of no info
