### ISSUE TITLE
Timestamp of Attachment ist not set

### ISSUE THREAD

**Issue by Blackskyliner** [malko/rocketchat-gitlab-hook#23]
Problem: All Attachements are missing the 'ts' portion of the message. Thus leading to 1.1.1970 00:00 in the cite of the Botmessage.

Possible solution: We get dates throughout the gitlab pushes, it's within commits (timestamp) and within object_attributes (created_at). So I guess weshould extend the makeAttachement function and add the parameter timestamp and fill it with the corresponding dates and times.

**Comment by malko** [comment]
Hi, I miss time at the moment to work and try on this, but PR/MR is welcome.
Thanks for your proposal anyway.

**Comment by mcsage** [comment]
+1

**Comment by malko** [comment]
Thanks to @Blackskyliner
