### ISSUE TITLE
Error while send push event 

### ISSUE THREAD

**Issue by rajivfx** [malko/rocketchat-gitlab-hook#28]
Error occured while parsing an incoming webhook request. Details attached.
Error: 'TypeError: Cannot read property 'web_url' of undefined', 
Message: 'Cannot read property 'web_url' of undefined', 
Stack: 'TypeError: Cannot read property 'web_url' of undefined
at Script.pushEvent (script.js:1:7204)
at Script.process_incoming_request (script.js:1:2109)
at Fiber (evalmachine.<anonymous>:6:23)'

**Comment by malko** [comment]
Is there any else concerned ?

**Comment by willstott101** [comment]
This is happening to me as well, not currently sure how to find the json we're actually receiving, but I am trying to setup system-wide events. Perhaps it's a problem with system hooks vs project hooks.

**Comment by willstott101** [comment]
My PR https://github.com/malko/rocketchat-gitlab-hook/pull/31 has resolved all errors on our instance. They were all to do with using System Hooks rather than per-project hooks. I cannot be sure if that's the same cause of @vfxpandit 's erros but it seems likely.

**Comment by malko** [comment]
latest version incorporate modification from this PR
