### ISSUE TITLE
Avatar of private projects not displayed correctly.

### ISSUE THREAD

**Issue by SevenOutman** [malko/rocketchat-gitlab-hook#29]
I've run into this problem that when the webhook post a message for a push event, its avatar was missing. I inspected the DOM and found that the avatar image url was the avatar for that project/repository. Since the repository was private, requests for its url (especially sent from rocket client) were blocked and redirected to the signin page. I guess the script should avoid using project's avatar when it's not public accessible.

**Comment by malko** [comment]
Yes would be fine, can you please make amerge request ?

**Comment by malko** [comment]
no more activity on this closing.
