### ISSUE TITLE
Tag event doesn't work anymore

### ISSUE THREAD

**Issue by MarcDahlem** [malko/rocketchat-gitlab-hook#3]
Hi Malko,

thanks for the new update(s) of the script.
Today, I updated the script in our Rocket.Chat.
Since that, the tag events do not show up anymore in our webhook channel.

Best regards
Marc

**Comment by malko** [comment]
you can now enable @all mentions by setting 

```
const MENTION_ALL_ALLOWED = true; // <- check that bot permission allow has mention-all before passing this to true.
```

at the start of the file
