### ISSUE TITLE
Does it work with Rocketchat 3.11.0?

### ISSUE THREAD

**Issue by mstoetzer** [malko/rocketchat-gitlab-hook#33]
Has anybody tested this Webhook script with the latest Rocketchat version? :)

**Comment by malko** [comment]
I can't tell I'm not using rocket chat anymore if someone can test the latest version and report it would be nice

**Comment by TipiT** [comment]
I does work, except https://github.com/malko/rocketchat-gitlab-hook/issues/36 :)

**Comment by malko** [comment]
Thanks for the report, will look into #36 asap
