### ISSUE TITLE
Messages should have a target="_blank" attribute in html a tags

### ISSUE THREAD

**Issue by fseraphine** [malko/rocketchat-gitlab-hook#37]
In version 5.4.4 (at least), RocketChat opens links embedded in messages generated by this hook script by replacing the current page (either in the web interface or in the desktop client).

Links generated by this hook script doesn't have a `target="_blank"`  attribute in the html a tags :

![message-without-target](https://user-images.githubusercontent.com/5850015/236156393-dbbc8b60-731b-4cc5-83d0-be46b102821d.png)

whereas a message created by typing an url in the chat has a `target="_blank"`  attribute and opens correctly in a browser window or tab. :
![message-with-target](https://user-images.githubusercontent.com/5850015/236156828-fc09b860-ad23-4af8-a7be-e6b4c9d858f7.png)

**Comment by malko** [comment]
Hi @fseraphine,

Can you please try to change the line 257 from: 
```
makeAttachment(user, `${mr.action} MR [#${mr.iid} ${mr.title}](${mr.url})\n${mr.source_branch} into ${mr.target_branch}`, mr.updated_at)
```

to: 
```
makeAttachment(user, `${mr.action} MR <a href="${mr.url}" target="_blank">#${mr.iid} ${mr.title}]</a>\n${mr.source_branch} into ${mr.target_branch}`, mr.updated_at)
```

And tell me if this solve the problem or make things worse :)

**Comment by fseraphine** [comment]
Hi Malko,

Your proposition doesn't solve the issue. Now we have a message with the html code :

![image](https://user-images.githubusercontent.com/5850015/236428279-e21c246e-31ef-4030-918f-4dac4ae4509a.png)

**Comment by malko** [comment]
I was afraid of that answer :confused: 

The problem should then be reported to rocket-chat, as it is due to the markdown parser of rocket-chat not adding the target to the link. Just to be sure, is the domain name of your gitlab the same as your rocket-chat server, or only a relative url (could be a track to follow) ? I've looked into their markdown supported syntax and didn't find a way to precise the link as being external.

Sorry but I don't see a fix on the hook side.

**Comment by malko** [comment]
Doing some research perhaps one more thing to try (depending on their markdown engine), 
replace the line 257 with: 
```
makeAttachment(user, `${mr.action} MR [#${mr.iid} ${mr.title}](${mr.url}){:target="_blank"}\n${mr.source_branch} into ${mr.target_branch}`, mr.updated_at)
```
@fseraphine can you tell me what it looks like?

**Comment by fseraphine** [comment]
I tried this one but I don't have the response from the dev team. I'll try on my personal setup this weekend.

I'll keep you posted. And if it doesn't solve the issue, I'll try to upgrade RocketChat to version 6.

Thank you very much for your help.

**Comment by fseraphine** [comment]
Hello Malko,
I found out that the bug is fixed at least in rocket.chat:6.1.7.
There was an issue opened https://github.com/RocketChat/Rocket.Chat/issues/27761
Thanks for you kind help
