### ISSUE TITLE
Confidential issues are not handled - unknown event

### ISSUE THREAD

**Issue by tholu** [malko/rocketchat-gitlab-hook#8]
Steps to reproduce: 

1. Create a confidential issue in Gitlab.
2. `Unknown event 'Confidential Issue Hook' occured. Data attached.`

**Comment by malko** [comment]
What should be the attended behavior? ignore this hook or display it as a normal issue hook ?

**Comment by tholu** [comment]
A config switch would be the best option, so one can decide if confidential hooks should be displayed or not (e.g. for integrations associated to different channels).

**Comment by malko** [comment]
IGNORE_CONFIDENTIAL = true added at the start of the file, put it to false if you want to have them.
